gui:
  theme:
    selectedLineBgColor:
      # - "#314154"
      - "#013e4a"
  expandFocusedSidePanel: true
  language: en
  mouseEvents: false
  nerdFontsVersion: "3"

# Keybindings
keybinding:
  universal:
    prevItem-alt: "u"
    nextItem-alt: "e"
    prevBlock-alt: "n"
    nextBlock-alt: "i"
    scrollUpMain-alt1: "U"
    scrollDownMain-alt1: "E"
    scrollLeft: "N"
    scrollRight: "I"
    nextMatch: "-"
    prevMatch: "="
    new: "k"
    edit: "o"
    openFile: "O"
    undo: "l"
    redo: "L"
    quit: <esc>
    quitWithoutChangingDirectory: <backspace>
  
  status:
    checkForUpdate: <disabled>
  
  files:
    ignoreFile: "h"
  
  branches:
    viewGitFlowOptions: "I"
    setUpstream: "s"
  
  commits:
    moveUpCommit: "<c-u>"
    moveDownCommit: "<c-e>"
    startInteractiveRebase: "I"

# Commande personnalisÃ©e pour GitHub PR
customCommands:
  - key: "v"
    context: "localBranches"
    loadingText: "Checking out GitHub Pull Request..."
    command: "gh pr checkout {{.Form.PullRequestNumber}}"
    prompts:
      - type: "menuFromCommand"
        title: "Which PR do you want to check out?"
        key: "PullRequestNumber"
        command: >-
          gh pr list --json number,title,headRefName,updatedAt
          --template '{{`{{range .}}{{printf "#%v: %s - %s (%s)" .number .title .headRefName (timeago .updatedAt)}}{{end}}`}}'
        filter: "#(?P<number>[0-9]+): (?P<title>.+) - (?P<ref_name>[^ ]+).*"
        valueFormat: "{{.number}}"
        labelFormat: '{{"#" | black | bold}}{{.number | white | bold}} {{.title | yellow | bold}}{{" [" | black | bold}}{{.ref_name | green}}{{"]" | black | bold}}'

os:
  # This allows me to open Neovide when press "e" to edit a file in lazygit, it
  # works when I'm inside neovim
  # https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#configuring-file-editing
  # Otherwise, the snacks neovim plugin has configured the `nvim-remote` preset
  # by default
  # https://github.com/folke/snacks.nvim/blob/main/docs/lazygit.md
  #
  # You can add `>/dev/null 2>&1 &` at the end of each option so that the
  # lazygit in the terminal is not locked while neovide is open
  # edit: 'NVIM_APPNAME="neobean" Neovide {{filename}} >/dev/null 2>&1 &'
  # editAtLine: 'NVIM_APPNAME="neobean" Neovide -- {{filename}} --line={{line}} >/dev/null 2>&1 &'
  edit: 'NVIM_APPNAME="neobean" Neovide {{filename}}'
  editAtLine: 'NVIM_APPNAME="neobean" Neovide -- {{filename}} --line={{line}}'
  #
  # editAtLineAndWait: 'NVIM_APPNAME="neobean" Neovide -- {{filename}} --line={{line}}'
  #
  # If this is set to true, when editing a file from lazygit, it opens it in the
  # terminal, instead of Neovide, and you cannot go back to lazygit
  editInTerminal: false

  # # This is the snacks neovim plugin default option, if you want to use it,
  # # comment all the options above
  # # https://github.com/folke/snacks.nvim/blob/main/docs/lazygit.md
  # editPreset: "nvim-remote"

git:
  paging:
    colorArg: always
    # For this to work, first install `brew install git-delta`
    # https://github.com/dandavison/delta
    # https://github.com/jesseduffield/lazygit/issues/155#issuecomment-2260986940
    pager: delta --dark --paging=never --syntax-theme base16-256 -s
    externalDiffCommand: difft --color=always --display=inline --syntax-highlight=off

update:
  method: never

notARepository: "quit"
promptToReturnFromSubprocess: false
quitOnTopLevelReturn: true
